### ISSUE TITLE
Compatibility with latest version of otel

### ISSUE THREAD

**Issue by kesavkolla** [LukeMathWalker/tracing-actix-web#32]
I wanted to try otel 0.15 when I tried to change the references to new version code breaks.

Cargo.toml
```toml
[dependencies]
tracing = "0.1.19"
opentelemetry = { version = "0.15", features = ["rt-tokio-current-thread"] }
opentelemetry-jaeger = { version = "0.13", features = ["tokio"] }
tracing-opentelemetry = { version = "0.13" }
tracing-subscriber = { version = "0.2.12", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.1.6"
tokio = { version = "1", features = ["full"] }
actix-web = "4.0.0-beta.8"
tracing-actix-web = { git = "https://github.com/LukeMathWalker/tracing-actix-web", features = ["opentelemetry_0_15"] }
```

The init code:
```rust
fn init_telemetry() {
    let app_name = concat!(env!("CARGO_PKG_NAME"), ":", env!("CARGO_PKG_VERSION"));

    // Start a new Jaeger trace pipeline.
    // Spans are exported in batch - recommended setup for a production application.
    global::set_text_map_propagator(TraceContextPropagator::new());
    let tracer = opentelemetry_jaeger::new_pipeline()
        .with_service_name(app_name)
        .install_batch(TokioCurrentThread)
        .expect("Failed to install OpenTelemetry tracer.");

    // Filter based on level - trace, debug, info, warn, error
    // Tunable via `RUST_LOG` env variable
    let env_filter = EnvFilter::try_from_default_env().unwrap_or(EnvFilter::new("info"));
    // Create a `tracing` layer using the Jaeger tracer
    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    // Create a `tracing` layer to emit spans as structured logs to stdout
    let formatting_layer = BunyanFormattingLayer::new(app_name.into(), std::io::stdout);
    // Combined them all together in a `tracing` subscriber
    let subscriber = Registry::default()
        .with(env_filter)
        .with(telemetry)
        .with(JsonStorageLayer)
        .with(formatting_layer);
    tracing::subscriber::set_global_default(subscriber)
        .expect("Failed to install `tracing` subscriber.")
}
```

Error:

```
error[E0277]: the trait bound `TokioCurrentThread: opentelemetry::runtime::Runtime` is not satisfied
   --> src/main.rs:26:24
    |
26  |         .install_batch(TokioCurrentThread)
    |                        ^^^^^^^^^^^^^^^^^^ the trait `opentelemetry::runtime::Runtime` is not implemented for `TokioCurrentThread`
    |
help: trait impl with same name found
   --> /home/kesav/.cargo/registry/src/github.com-1ecc6299db9ec823/opentelemetry-0.15.0/src/runtime.rs:78:1
    |
78  | / impl Runtime for TokioCurrentThread {
79  | |     type Interval = tokio_stream::wrappers::IntervalStream;
80  | |     type Delay = tokio::time::Sleep;
81  | |
...   |
104 | |     }
105 | | }
    | |_^
    = note: perhaps two different versions of crate `opentelemetry` are being used?

```
