### ISSUE TITLE
No logs emitted

### ISSUE THREAD

**Issue by RemiKalbe** [LukeMathWalker/tracing-actix-web#67]
Not sure what I did wrong but I don't have any logs from actix anymore (after switching from actix's default logger to this crate), except errors, for example:
```
{"timestamp":"2022-01-14T17:20:52.642643550+00:00","level":"WARN","fields":{"message":"Error encountered while processing the incoming HTTP request: Deserialize(Error(\"missing field `server_room_id`\", line: 1, column: 108))"},"target":"tracing_actix_web::middleware","trace_id":"e9e3e403ef820f16f26eec02879f963f"}
```
I was expecting to get logs of each requests. Like actix-web's Logger was doing. 
(The EnvFilter is set to info)

Here is how my tracing_subcriber is configured
```rust
let filter = EnvFilter::try_from_default_env()
    .or_else(|_| EnvFilter::try_new("info"))
    .unwrap();

let opentelemetry_endpoint = env::var("OPENTELEMETRY_ENDPOINT").expect("Missing env var 'OPENTELEMETRY_ENDPOINT''");

let exporter = opentelemetry_otlp::new_exporter()
    .tonic()
    .with_endpoint(opentelemetry_endpoint);

let config = opentelemetry::sdk::trace::config()
    .with_resource(opentelemetry::sdk::Resource::new(vec![
        opentelemetry::KeyValue::new("service.name", "media-server"),
        opentelemetry::KeyValue::new("service.namespace", "cloud-conference"),
]));

let tracer = opentelemetry_otlp::new_pipeline()
    .tracing()
    .with_exporter(exporter)
    .with_trace_config(config)
    .install_batch(opentelemetry::runtime::Tokio)
    .expect("Failed to create opentelemtry pipeline");

let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);

let subscriber =                         
    tracing_subscriber::fmt::layer().json().with_current_span(true).event_format(tracing_bridge::TraceIdFormat);

tracing_subscriber::registry()
    .with(telemetry)
    .with(filter)
    .with(subscriber)
    .try_init()
    unwrap();
```
And then the actix middleware is setup like that.
```rust
let start_server = HttpServer::new(move || {
App::new()
    .wrap(TracingLogger::default())
    ......
```
My cargo
```toml
...
actix-web = "4.0.0-beta.19"
actix-http = "3.0.0-beta.18"
tracing-actix-web = { version = "0.5.0-beta.9", features = ["opentelemetry_0_16"]}
tracing = "0.1"
tracing-futures = "0.2"
tracing-log = { version = "0.1", features = ["env_logger"] }
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.5", features = ["env-filter", "json", "fmt"] }
tracing-serde = "0.1.2"
...
```
